databases:
  - name: maineum
    user: maineum
    plan: free
    region: ohio

services:
  - type: web
    name: maineum
    plan: free
    region: ohio
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maineum
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false